# Generated by Django 5.2.4 on 2026-07-17 09:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rights_basis', models.CharField(choices=[('owned', 'Owned'), ('commissioned', 'Commissioned'), ('licensed', 'Licensed'), ('public_domain', 'Public domain'), ('permission_granted', 'Permission granted')], max_length=32)),
                ('rights_holder', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('evidence_reference', models.CharField(blank=True, max_length=500)),
                ('licence_name', models.CharField(blank=True, max_length=200)),
                ('licence_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allows_public_display', models.BooleanField(default=False)),
                ('allows_ai_input', models.BooleanField(default=False)),
                ('allows_derivative_generation', models.BooleanField(default=False)),
                ('allows_commercial_use', models.BooleanField(default=False)),
                ('attribution_required', models.BooleanField(default=False)),
                ('attribution_text', models.CharField(blank=True, max_length=500)),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_rights_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usage rights record',
                'verbose_name_plural': 'usage rights records',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspirationAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('garment_type', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lower-case machine identifier (letters, digits, underscores).', regex='^[a-z][a-z0-9_]{1,63}$')])),
                ('cultural_context', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('image_storage_key', models.CharField(blank=True, max_length=255)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=255)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('image_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Must be exactly 64 lower-case hexadecimal characters.', regex='^[0-9a-f]{64}$')])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiration_assets_approved', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiration_assets_uploaded', to=settings.AUTH_USER_MODEL)),
                ('usage_rights', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset', to='catalogue.usagerights')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='usagerights',
            constraint=models.CheckConstraint(condition=models.Q(('rights_basis__in', ['owned', 'commissioned', 'licensed', 'public_domain', 'permission_granted'])), name='catalogue_rights_basis_valid'),
        ),
        migrations.AddConstraint(
            model_name='usagerights',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['pending', 'verified', 'rejected'])), name='catalogue_rights_verification_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='usagerights',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='catalogue_rights_verified_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='usagerights',
            constraint=models.CheckConstraint(condition=models.Q(('attribution_required', False), models.Q(('attribution_text', ''), _negated=True), _connector='OR'), name='catalogue_rights_attribution_text_required'),
        ),
        migrations.AddConstraint(
            model_name='usagerights',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('verified_at__isnull', True), ('expires_at__gt', models.F('verified_at')), _connector='OR'), name='catalogue_rights_expiry_after_verification'),
        ),
        migrations.AddConstraint(
            model_name='inspirationasset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'retired'])), name='catalogue_asset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='inspirationasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_storage_key', ''), ('thumbnail_storage_key', ''), ('image_width__isnull', True), ('image_height__isnull', True), ('image_size_bytes__isnull', True), ('image_sha256', '')), models.Q(models.Q(('image_storage_key', ''), _negated=True), models.Q(('thumbnail_storage_key', ''), _negated=True), ('image_width__isnull', False), ('image_height__isnull', False), ('image_size_bytes__isnull', False), models.Q(('image_sha256', ''), _negated=True)), _connector='OR'), name='catalogue_asset_image_metadata_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='inspirationasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='catalogue_asset_approved_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='inspirationasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_width__isnull', True), ('image_width__gt', 0), _connector='OR'), models.Q(('image_height__isnull', True), ('image_height__gt', 0), _connector='OR'), models.Q(('image_size_bytes__isnull', True), ('image_size_bytes__gt', 0), _connector='OR')), name='catalogue_asset_image_facts_positive'),
        ),
    ]
