# Generated by Django 5.2.4 on 2026-07-16 17:54, then extended with a
# collision preflight and canonical normalisation.
#
# 1. Detects existing collisions under Lower(Trim(email)) — case AND
#    whitespace variants — and FAILS with a safe count-only message before
#    modifying anything; accounts are never merged or deleted.
# 2. Normalises existing non-colliding rows to the canonical form.
# 3. Replaces the Lower(email) uniqueness with Lower(Trim(email)) uniqueness
#    plus a check constraint requiring stored values to already be
#    canonical, closing bulk_create()/QuerySet.update() bypasses.

import django.db.models.functions.text
from django.db import migrations, models

from sitara.accounts.migration_utils import (
    collision_error_message,
    count_canonical_email_collisions,
)


def preflight_and_normalize(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    collisions = count_canonical_email_collisions(User.objects.all())
    if collisions:
        raise RuntimeError(collision_error_message(collisions))

    for user in User.objects.all().iterator():
        canonical = (user.email or "").strip().lower()
        if canonical != user.email:
            user.email = canonical
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_case_insensitive'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(preflight_and_normalize, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_email_ci_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), name='accounts_user_email_canonical_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')))), name='accounts_user_email_is_canonical'),
        ),
    ]
