# Generated by Django 5.2.4 on 2026-07-17 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('designs', '0001_initial'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='questionnaire_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='questionnaire.questionnaireversion'),
        ),
        migrations.CreateModel(
            name='DesignInspiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_selections', to='designs.design')),
                ('inspiration_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_selections', to='catalogue.inspirationasset')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('design', 'inspiration_asset'), name='designs_inspiration_unique_asset_per_design'), models.UniqueConstraint(fields=('design', 'position'), name='designs_inspiration_unique_position_per_design'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='designs_inspiration_position_bounds')],
            },
        ),
    ]
