# Generated by Django 5.2.4 on 2026-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_questionnaire_version_designinspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='design_spec_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design_spec_template_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('design_spec__isnull', True), ('design_spec_schema_version__isnull', True), ('design_spec_template_version', ''), ('design_spec_provider', ''), ('design_spec_model', ''), ('design_spec_generated_at__isnull', True)), models.Q(('design_spec__isnull', False), ('design_spec_schema_version__isnull', False), models.Q(('design_spec_template_version', ''), _negated=True), models.Q(('design_spec_provider', ''), _negated=True), models.Q(('design_spec_model', ''), _negated=True), ('design_spec_generated_at__isnull', False)), _connector='OR'), name='designs_designversion_spec_provenance_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('design_spec_input_tokens__isnull', True), ('design_spec_input_tokens__gt', 0), _connector='OR'), models.Q(('design_spec_output_tokens__isnull', True), ('design_spec_output_tokens__gt', 0), _connector='OR')), name='designs_designversion_spec_tokens_positive'),
        ),
    ]
