# Generated by Django 5.2.4 on 2026-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_designversion_design_spec_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='prompt_builder_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_prompt', ''), ('prompt_builder_version', '')), models.Q(models.Q(('image_prompt', ''), _negated=True), models.Q(('prompt_builder_version', ''), _negated=True)), _connector='OR'), name='designs_designversion_image_prompt_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('image_prompt', ''), ('design_spec__isnull', False), _connector='OR'), name='designs_designversion_image_prompt_requires_spec'),
        ),
    ]
