# Generated by Django 5.2.4 on 2026-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_generationattempt_async_pipeline'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('staged_image_sha256', ''), ('staged_image_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_attempt_sha256_shape'),
        ),
    ]
