# Generated by Django 5.2.4 on 2026-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_generationattempt_designs_attempt_sha256_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationattempt',
            name='text_submission_in_flight',
            field=models.BooleanField(default=False),
        ),
    ]
