# Generated by Django 5.2.4 on 2026-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_generationattempt_text_submission_in_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='image_ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='image_processor_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='designversion',
            name='image_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='designversion',
            name='image_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='thumbnail_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='designversion',
            name='thumbnail_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='thumbnail_storage_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='designversion',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_storage_key', ''), ('image_sha256', ''), ('image_size_bytes__isnull', True), ('image_width__isnull', True), ('image_height__isnull', True), ('thumbnail_storage_key', ''), ('thumbnail_sha256', ''), ('thumbnail_size_bytes__isnull', True), ('thumbnail_width__isnull', True), ('thumbnail_height__isnull', True), ('image_processor_version', ''), ('image_ingested_at__isnull', True)), models.Q(models.Q(('image_storage_key', ''), _negated=True), models.Q(('image_sha256', ''), _negated=True), ('image_size_bytes__isnull', False), ('image_width__isnull', False), ('image_height__isnull', False), models.Q(('thumbnail_storage_key', ''), _negated=True), models.Q(('thumbnail_sha256', ''), _negated=True), ('thumbnail_size_bytes__isnull', False), ('thumbnail_width__isnull', False), ('thumbnail_height__isnull', False), models.Q(('image_processor_version', ''), _negated=True), ('image_ingested_at__isnull', False)), _connector='OR'), name='designs_designversion_permanent_image_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('image_sha256', ''), ('image_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_designversion_image_sha256_shape'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('thumbnail_sha256', ''), ('thumbnail_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_designversion_thumbnail_sha256_shape'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_size_bytes__isnull', True), ('image_size_bytes__gt', 0), _connector='OR'), models.Q(('image_width__isnull', True), ('image_width__gt', 0), _connector='OR'), models.Q(('image_height__isnull', True), ('image_height__gt', 0), _connector='OR'), models.Q(('thumbnail_size_bytes__isnull', True), ('thumbnail_size_bytes__gt', 0), _connector='OR'), models.Q(('thumbnail_width__isnull', True), ('thumbnail_width__gt', 0), _connector='OR'), models.Q(('thumbnail_height__isnull', True), ('thumbnail_height__gt', 0), _connector='OR')), name='designs_designversion_permanent_image_positive'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('image_storage_key', ''), ('thumbnail_storage_key', ''), models.Q(('image_storage_key', models.F('thumbnail_storage_key')), _negated=True), _connector='OR'), name='designs_designversion_image_keys_differ'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('image_storage_key', ''), models.Q(('design_spec__isnull', False), models.Q(('image_prompt', ''), _negated=True), models.Q(('prompt_builder_version', ''), _negated=True)), _connector='OR'), name='designs_designversion_permanent_image_requires_spec_prompt'),
        ),
    ]
