# Generated by Django 5.2.4 on 2026-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_designversion_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='inspiration_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='inspiration_context_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='inspiration_context_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inspiration_context__isnull', True), ('inspiration_context_schema_version__isnull', True), ('inspiration_context_sha256', '')), models.Q(('inspiration_context__isnull', False), ('inspiration_context_schema_version__isnull', False), models.Q(('inspiration_context_sha256', ''), _negated=True)), _connector='OR'), name='designs_designversion_inspiration_context_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('inspiration_context__isnull', True), ('inspiration_context_schema_version', 1), _connector='OR'), name='designs_designversion_inspiration_context_schema_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('inspiration_context_sha256', ''), ('inspiration_context_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_designversion_inspiration_context_sha256_shape'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('inspiration_context__isnull', True), ('design_spec__isnull', False), _connector='OR'), name='designs_designversion_inspiration_context_requires_spec'),
        ),
    ]
