# Generated by Django 5.2.4 on 2026-07-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_designversion_inspiration_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refined_versions', to='designs.designversion'),
        ),
        migrations.AddField(
            model_name='designversion',
            name='refinement_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='refinement_request_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='refinement_request_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='generation_kind',
            field=models.CharField(choices=[('initial', 'Initial'), ('refinement', 'Refinement')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='seed_reused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='source_design_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinement_attempts', to='designs.designversion'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refinement_request__isnull', True), ('refinement_request_schema_version__isnull', True), ('refinement_request_sha256', '')), models.Q(('refinement_request__isnull', False), ('refinement_request_schema_version__isnull', False), models.Q(('refinement_request_sha256', ''), _negated=True)), _connector='OR'), name='designs_designversion_refinement_request_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('refinement_request_schema_version__isnull', True), ('refinement_request_schema_version', 1), _connector='OR'), name='designs_designversion_refinement_request_schema_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('refinement_request_sha256', ''), ('refinement_request_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_designversion_refinement_request_sha256_shape'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('refinement_request__isnull', True), ('parent_version__isnull', False), _connector='OR'), name='designs_designversion_refinement_request_requires_parent'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('parent_version__isnull', True), ('refinement_request__isnull', False), _connector='OR'), name='designs_designversion_parent_requires_refinement_request'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(('parent_version__isnull', True), models.Q(('parent_version', models.F('id')), _negated=True), _connector='OR'), name='designs_designversion_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('version_number', 1), _negated=True), ('parent_version__isnull', True), _connector='OR'), name='designs_designversion_v1_no_parent'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('version_number', 2), _negated=True), ('parent_version__isnull', False), _connector='OR'), name='designs_designversion_v2_requires_parent'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('generation_kind__in', ['initial', 'refinement'])), name='designs_attempt_generation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generation_kind', 'initial'), ('source_design_version__isnull', True)), models.Q(('generation_kind', 'refinement'), ('source_design_version__isnull', False)), _connector='OR'), name='designs_attempt_generation_kind_source_version_consistent'),
        ),
    ]
