# Generated by Django 5.2.4 on 2026-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_designversion_parent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationattempt',
            name='refinement_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='refinement_request_schema_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='refinement_request_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refinement_request__isnull', True), ('refinement_request_schema_version__isnull', True), ('refinement_request_sha256', '')), models.Q(('refinement_request__isnull', False), ('refinement_request_schema_version__isnull', False), models.Q(('refinement_request_sha256', ''), _negated=True)), _connector='OR'), name='designs_attempt_refinement_request_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('refinement_request_schema_version__isnull', True), ('refinement_request_schema_version', 1), _connector='OR'), name='designs_attempt_refinement_request_schema_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('refinement_request_sha256', ''), ('refinement_request_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='designs_attempt_refinement_request_sha256_shape'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generation_kind', 'initial'), ('refinement_request__isnull', True)), models.Q(('generation_kind', 'refinement'), ('refinement_request__isnull', False)), _connector='OR'), name='designs_attempt_generation_kind_refinement_request_consistent'),
        ),
    ]
