# Generated by Django 5.2.4 on 2026-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_generationattempt_refinement_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designversion',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='demo_selection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('demo_selection__isnull', True), ('is_demo', True), _connector='OR'), name='designs_attempt_demo_selection_requires_demo'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), models.Q(('is_demo', True), _negated=True), ('demo_selection__isnull', False), _connector='OR'), name='designs_attempt_demo_succeeded_requires_selection'),
        ),
    ]
