# Generated by Django 5.2.4 on 2026-07-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_generation_attempt_designversion_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationattempt',
            name='accounted_input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='accounted_output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_accounting_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_estimated_micro_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_pricing_profile_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_reserved_micro_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_unresolved_micro_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('cost_reserved_micro_usd__gte', 0), ('cost_estimated_micro_usd__gte', 0), ('cost_unresolved_micro_usd__gte', 0)), name='designs_attempt_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('cost_estimated_micro_usd__lte', models.F('cost_reserved_micro_usd'))), name='designs_attempt_cost_estimated_within_reserved'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('cost_unresolved_micro_usd__lte', models.F('cost_estimated_micro_usd'))), name='designs_attempt_cost_unresolved_within_estimated'),
        ),
    ]
