# Generated by Django 5.2.4 on 2026-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0013_generationattempt_accounted_input_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='generationattempt',
            name='designs_attempt_cost_non_negative',
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_accounting_settled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='cost_overage_micro_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('cost_reserved_micro_usd__gte', 0), ('cost_estimated_micro_usd__gte', 0), ('cost_unresolved_micro_usd__gte', 0), ('cost_overage_micro_usd__gte', 0)), name='designs_attempt_cost_non_negative'),
        ),
    ]
