# Generated by Django 5.2.4 on 2026-07-29 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0014_remove_generationattempt_designs_attempt_cost_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignInspirationUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('image_size_bytes', models.PositiveIntegerField()),
                ('image_sha256', models.CharField(max_length=64)),
                ('rights_acknowledged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_uploads', to='designs.design')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('design', 'position'), name='designs_upload_unique_position_per_design'), models.UniqueConstraint(fields=('design', 'image_sha256'), name='designs_upload_unique_image_per_design'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='designs_upload_position_bounds'), models.CheckConstraint(condition=models.Q(('storage_key', ''), _negated=True), name='designs_upload_storage_key_present')],
            },
        ),
    ]
