# Generated by Django 5.2.4 on 2026-08-06 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0015_design_inspiration_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignAnnotationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('document', models.JSONField()),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_document', to='designs.designversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='designs_annotation_revision_positive'), models.CheckConstraint(condition=models.Q(('schema_version', 1)), name='designs_annotation_schema_version_valid')],
            },
        ),
    ]
