# Generated by Django 5.2.4 on 2026-08-07 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0016_designannotationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRenderDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('plain', 'Plain render'), ('annotated', 'Annotated render')], max_length=16)),
                ('state', models.CharField(choices=[('claimed', 'Claimed'), ('sent', 'Sent'), ('retry_exhausted', 'Retry exhausted')], max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField()),
                ('claimed_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_deliveries', to='designs.designversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('design_version', 'kind'), name='designs_render_delivery_unique_version_kind'), models.CheckConstraint(condition=models.Q(('state__in', ['claimed', 'sent', 'retry_exhausted'])), name='designs_render_delivery_state_valid'), models.CheckConstraint(condition=models.Q(('kind__in', ['plain', 'annotated'])), name='designs_render_delivery_kind_valid'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', 1), ('attempt_count__lte', 2)), name='designs_render_delivery_attempt_count_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('state', 'sent')), models.Q(models.Q(('state', 'sent'), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='designs_render_delivery_sent_at_matches_state')],
            },
        ),
    ]
