# Generated by Django 5.2.4 on 2026-08-09 11:59

from django.db import migrations, models


def count_the_send_each_existing_marker_already_made(apps, schema_editor):
    """Give every already-sent marker the count its timestamp implies.

    Until this migration a `sent` row meant exactly one delivered message and
    nothing recorded how many, because one was the only possible answer. The new
    `sent_at IS NOT NULL <=> send_count > 0` constraint is added AFTER this runs,
    so without this step every historical row would violate it the moment the
    constraint appeared.

    Literals and the historical model only — no runtime application function is
    imported here, so a later change to the delivery service cannot alter what
    this migration did."""
    delivery = apps.get_model("designs", "DesignRenderDelivery")
    delivery.objects.filter(state="sent").update(send_count=1)


def nothing_to_undo(apps, schema_editor):
    """The reverse direction needs no data work, and saying so is the honest form.

    An earlier version of this zeroed `send_count` on the way back, on the
    reasoning that a leftover count would leave rows the forward direction could
    not re-migrate. That reasoning does not survive the operation order: the
    reverse drops the column immediately afterwards, so no value can persist to
    be re-migrated, and re-applying the migration re-adds the column at its
    default before this function's forward twin runs again.

    A named no-op rather than `RunPython.noop` so this reasoning has somewhere to
    live — the reverse being empty is a conclusion, not an oversight."""


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0017_designrenderdelivery'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designrenderdelivery',
            name='designs_render_delivery_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='designrenderdelivery',
            name='designs_render_delivery_attempt_count_bounded',
        ),
        migrations.RemoveConstraint(
            model_name='designrenderdelivery',
            name='designs_render_delivery_sent_at_matches_state',
        ),
        migrations.AddField(
            model_name='designrenderdelivery',
            name='attempt_epoch',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='designrenderdelivery',
            name='requested_filename',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='designrenderdelivery',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            count_the_send_each_existing_marker_already_made,
            nothing_to_undo,
            elidable=False,
        ),
        migrations.AlterField(
            model_name='designrenderdelivery',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('retry_exhausted', 'Retry exhausted')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='designrenderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'claimed', 'sent', 'retry_exhausted'])), name='designs_render_delivery_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='designrenderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0), ('attempt_count__lte', 2)), name='designs_render_delivery_attempt_count_bounded'),
        ),
        migrations.AddConstraint(
            model_name='designrenderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt_count', 0), ('state', 'pending')), models.Q(models.Q(('state', 'pending'), _negated=True), ('attempt_count__gte', 1)), _connector='OR'), name='designs_render_delivery_attempt_count_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='designrenderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_epoch__gte', 1)), name='designs_render_delivery_attempt_epoch_positive'),
        ),
        migrations.AddConstraint(
            model_name='designrenderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('send_count__gt', 0), ('sent_at__isnull', False)), models.Q(('send_count', 0), ('sent_at__isnull', True)), _connector='OR'), name='designs_render_delivery_sent_at_matches_send_count'),
        ),
    ]
