# Generated by Django 5.2.4 on 2026-08-12 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0018_render_delivery_send_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceUploadGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_upload_grants', to='designs.design')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['design', 'revoked_at'], name='designs_grant_design_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('token_digest', ''), _negated=True), name='designs_grant_digest_present'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='designs_grant_expiry_after_creation'), models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('design',), name='designs_grant_one_live_per_design')],
            },
        ),
    ]
