// Privacy information (Phase 17 §16). A static server component: there is
// nothing here to fetch, and nothing here depends on who is reading.
//
// Every sentence below describes behaviour this repository actually
// implements. In particular it does NOT invent a retention period, a deletion
// window, a provider guarantee or a legal conclusion, and it does not describe
// the reference-image exposure ADR 0019 accepted as though it had been
// removed. Where the honest answer is "we do not publish that", it says so.

import type { Metadata } from "next";
import Link from "next/link";

import { AppShell } from "@/components/AppShell";

export const metadata: Metadata = {
  title: "Privacy — Sitara",
  description: "How Sitara keeps your bridalwear designs private, and what leaves Sitara when a concept is generated.",
};

export default function PrivacyPage() {
  return (
    <AppShell width="narrow">
      <p className="kicker">Privacy</p>
      <h1>Your designs are private by default</h1>
      <p className="lede">
        Nothing you create in Sitara is published, listed or shown to anyone else. There is no
        public gallery and no shareable design page.
      </p>

      <section className="panel" aria-labelledby="privacy-ownership">
        <h2 id="privacy-ownership">Who a design belongs to</h2>
        <p>
          If you have not signed in, your designs belong to the browser session you started them
          in. If you create an account or sign in, the designs from that session are claimed by
          your account and stay with it.
        </p>
        <p>
          A design is only ever readable by its owner. Knowing a design&apos;s address is not
          enough — a request from anyone else is answered exactly as a request for a design that
          does not exist, so Sitara never reveals whether someone else&apos;s design is there.
        </p>
        <p>
          A workspace already owned by one account is never transferred to another.
        </p>
      </section>

      <section className="panel" aria-labelledby="privacy-uploads">
        <h2 id="privacy-uploads">Inspiration images you upload</h2>
        <p>
          References you upload belong to your design alone. They are stored privately, are never
          added to Sitara&apos;s shared inspiration catalogue, and are never shown to other users
          or used to illustrate anyone else&apos;s design.
        </p>
        <p>
          Sitara asks you to confirm you have the right to use each image you upload. That
          confirmation is your statement, not a rights check Sitara has carried out — it is
          deliberately weaker than the staff-verified rights record behind a catalogue image, and
          Sitara does not present it as verified.
        </p>
      </section>

      <section className="panel" aria-labelledby="privacy-generation">
        <h2 id="privacy-generation">What leaves Sitara when a concept is generated</h2>
        <p>
          <strong>In demo mode</strong>, nothing leaves the machine. The brief is built locally and
          the image comes from a small reviewed set that ships with Sitara. No AI provider is
          contacted and no image of yours is sent anywhere.
        </p>
        <p>
          <strong>When a concept is generated by a live AI provider</strong>, two things are sent: a
          written description of the design, built from your answers; and the reference images you
          selected for that design — both your own uploads and any catalogue images you picked.
          Sitara sends the images themselves, as short-lived links the provider fetches once.
        </p>
        <p>
          This matters, so it is worth stating plainly rather than reassuringly. The image
          provider&apos;s terms take a perpetual, irrevocable licence over the inputs it receives,
          to train and improve its technology. Whether those terms extend to traffic routed through
          the intermediary Sitara uses is unresolved, and that intermediary publishes no retention
          window for inputs. Sitara cannot promise a reference image you send is deleted, and does
          not claim to.
        </p>
        <p>
          Sitara never sends a provider your email address, your account, your session, a storage
          location, an image&apos;s internal identifier, a title, an attribution line or any rights
          record. Only the design description and the images you chose.
        </p>
        <p>
          You do not have to upload anything. A concept can be generated from your answers alone.
        </p>
      </section>

      <section className="panel" aria-labelledby="privacy-storage">
        <h2 id="privacy-storage">Where your concepts are kept</h2>
        <p>
          Generated images are stored in private storage that is not readable from the public
          internet. When you view a concept, Sitara issues a temporary link for that one view.
        </p>
        <p>
          Those links are ordinary web addresses while they last: anyone holding one can open the
          image until it expires, and Sitara cannot withdraw one early. Treat a copied image link
          the way you would treat the image itself.
        </p>
      </section>

      <section className="panel" aria-labelledby="privacy-account">
        <h2 id="privacy-account">Your account</h2>
        <p>
          Signing in uses an ordinary session cookie. Sitara stores no login token in your browser
          and keeps no password in it. Signing out is confirmed by the server before Sitara treats
          you as signed out.
        </p>
      </section>

      <p>
        <Link href="/concepts">What an AI-assisted concept is — and is not</Link>
      </p>
    </AppShell>
  );
}
