/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap the CSRF token and browser session
         * @description Sets the sitara_csrftoken cookie and returns the matching token, and MATERIALISES the Django database session (setting sitara_sessionid) so later anonymous design operations can coordinate. Call this before any unsafe request. The token is never logged; the session key never leaves the backend.
         */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticates against a Django session. Failures for unknown email, wrong password and inactive accounts are one generic 401.
         */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Flushes the session and returns a fresh anonymous token. Idempotent: an anonymous browser gets the same shape of answer.
         */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session state
         * @description Browser session-state bootstrap. Returns the authenticated {id, email} user or an anonymous body — both are HTTP 200. Relies on the HttpOnly session cookie; anonymous access is intentional (no bearer token or API key is used).
         */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register and sign in
         * @description Creates an account and logs the browser in, rotating the session and token.
         */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public configuration
         * @description Safe, non-secret configuration for the frontend: demo mode, whether generation is available, and the inspiration/refinement limits. No authentication required; no tokens, credentials or storage details.
         */
        get: operations["config_public"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your designs
         * @description Returns the private designs owned by the current session or account as compact rows (no questionnaire schema, no inspiration records). A list request never creates a workspace. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_list"];
        put?: never;
        /**
         * Create a design
         * @description Creates a private draft. Accepts optional title, questionnaire version, answers and inspiration selections; status is server-owned (draft). Answers and inspirations are validated authoritatively and roll back together on any failure. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        post: operations["designs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a design
         * @description Returns the full draft: linked questionnaire (or null), answers and ordered inspiration selections with live availability. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a design
         * @description Partial draft update: title, questionnaire version (assignable once), answers (draft-validated) and inspiration selections (replaced as one ordered set). Only a draft — or a generation_failed design with no version, which returns to draft — may be edited. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        patch: operations["designs_update"];
        trace?: never;
    };
    "/api/v1/designs/{design_id}/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a design generation job
         * @description Enqueues one asynchronous generation job for a complete design and returns 202 with the public job payload and a same-origin Location header. Requires an Idempotency-Key UUID header; a repeated key returns the same job and queues no extra work. Accepts no body or exactly {}. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        post: operations["designs_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/refine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a single constrained refinement job
         * @description Enqueues one asynchronous refinement job editing the design's existing version-1 concept and returns 202 with the public job payload and a same-origin Location header. Requires an Idempotency-Key UUID header; a repeated key returns the same job and queues no extra work. The body names the source version, one allowlisted change_type and an optional bounded note — the note is untrusted preference data, safety-scanned before any provider call, and never echoed back. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        post: operations["designs_refine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/validate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a design draft
         * @description Performs NO generation. Re-checks the persisted draft with complete validation (every visible required question answered, minimum counts/lengths) and re-checks that every selected inspiration is still eligible. Returns {"valid": true} or a controlled 400 with question/selection errors. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        post: operations["designs_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/versions/{version_id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get short-lived signed image URLs for a design version
         * @description Returns presigned GET URLs for the version's private original and thumbnail WebP images, plus their dimensions and one shared expiry. The URLs are temporary bearer URLs: anyone possessing one may use it until it expires, and logout or session rotation does not revoke it — they are short-lived and must never be stored. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_version_images_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/versions/{version_id}/result/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the private concept result for a design version
         * @description Returns a purpose-built, curated result — title, concept summary and every DesignSpec section — revalidated and safety-scanned before delivery. Never exposes source_selections, questionnaire answers, the image prompt, provider/model/token provenance, storage keys, hashes or any signed URL. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_version_result_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process answers. No dependency checks. No authentication required.
         */
        get: operations["health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description PostgreSQL, the Redis broker, the auth-rate-limit cache and private object storage. Returns 503 with a displayable per-check body when any dependency is down. No authentication required.
         */
        get: operations["health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inspiration assets
         * @description Public, identity-free catalogue of rights-approved inspiration images (approved + verified + unexpired + all usage permissions). No authentication required; only the public fields are returned.
         */
        get: operations["inspiration_assets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/{asset_id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspiration asset image
         * @description Streams the full-size sanitised WebP for an eligible asset. No storage keys or storage URLs are exposed.
         */
        get: operations["inspiration_asset_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/{asset_id}/thumbnail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspiration asset thumbnail
         * @description Streams the thumbnail sanitised WebP for an eligible asset. No storage keys or storage URLs are exposed.
         */
        get: operations["inspiration_asset_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a generation job
         * @description Returns the public job payload (status, ids, timestamps, stable error code) for a job the caller owns. No prompt, DesignSpec, image URL or provider/storage provenance is ever exposed. Available even when live generation is currently disabled. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questionnaire/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active questionnaire
         * @description Serves the single active questionnaire version as {id, version, schema}. Public and identity-free (creates no session or workspace); no authentication required. The schema is the authoritative source of question types, constraints and compatibility rules.
         */
        get: operations["questionnaire_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `hide` - hide
         *     * `require` - require
         *     * `restrict_options` - restrict_options
         *     * `show` - show
         * @enum {string}
         */
        ActionEnum: "hide" | "require" | "restrict_options" | "show";
        ActiveQuestionnaireResponse: {
            /** Format: uuid */
            id: string;
            version: number;
            schema: components["schemas"]["QuestionnaireSchema"];
        };
        AuthSuccessResponse: {
            /** @description True on a successful login/registration. */
            authenticated: boolean;
            user: components["schemas"]["AuthUser"];
            /** @description Freshly rotated token to use going forward. */
            csrf_token: string;
        };
        AuthUser: {
            /**
             * Format: uuid
             * @description The user's UUID.
             */
            readonly id: string;
            /**
             * Format: email
             * @description Canonical (lower-cased) email.
             */
            readonly email: string;
        };
        /**
         * @description * `colour_story` - colour_story
         *     * `dupatta_or_saree_drape` - dupatta_or_saree_drape
         *     * `embellishment` - embellishment
         *     * `fabric_and_texture` - fabric_and_texture
         *     * `neckline` - neckline
         *     * `silhouette_detail` - silhouette_detail
         *     * `sleeves_and_coverage` - sleeves_and_coverage
         *     * `styling_details` - styling_details
         * @enum {string}
         */
        ChangeTypeEnum: "colour_story" | "dupatta_or_saree_drape" | "embellishment" | "fabric_and_texture" | "neckline" | "silhouette_detail" | "sleeves_and_coverage" | "styling_details";
        ColourStoryResult: {
            palette_summary: string;
            placement: string;
            rationale: string;
        };
        CompatibilityRuleSchema: {
            id: string;
            when: components["schemas"]["RuleConditionSchema"];
            then: components["schemas"]["RuleActionSchema"];
        };
        CoverageAndDrapeResult: {
            sleeves: string;
            neckline: string;
            back_and_midriff: string;
            head_covering: string;
            dupatta_or_saree_drape: string;
        };
        CsrfResponse: {
            /** @description Send this back as the X-CSRFToken header on unsafe requests. */
            csrf_token: string;
        };
        CulturalContextResult: {
            regional_direction: string | null;
            interpretation_notes: string[];
            safeguards: string[];
        };
        DesignDetailResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            questionnaire: components["schemas"]["DesignQuestionnaire"] | null;
            /** @description Answers keyed by stable question id. */
            answers: unknown;
            selected_inspirations: components["schemas"]["SelectedInspiration"][];
            latest_job: components["schemas"]["GenerationJob"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description One deliverable image: a short-lived signed URL plus its dimensions.
         *
         *     The URL is a TEMPORARY BEARER URL (usable by anyone holding it until
         *     expiry) — never persisted, cached or logged. No storage key, hash,
         *     provider/prediction id, seed or staging metadata is ever exposed.
         */
        DesignImage: {
            /** @description Short-lived signed GET URL for the private WebP object. */
            url: string;
            width: number;
            height: number;
        };
        DesignImages: {
            original: components["schemas"]["DesignOriginalImage"];
            thumbnail: components["schemas"]["DesignImage"];
            /**
             * Format: date-time
             * @description The single instant ALL THREE URLs stop working (ISO-8601).
             */
            expires_at: string;
        };
        /** @description A compact list row — no questionnaire schema, no inspiration records. */
        DesignListItem: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DesignListResponse: {
            designs: components["schemas"]["DesignListItem"][];
        };
        /**
         * @description The original image additionally carries a separately signed
         *     attachment URL (Phase 12) for a reliable download, sharing the same
         *     declared expiry as every other URL in the response.
         */
        DesignOriginalImage: {
            /** @description Short-lived signed GET URL for the private WebP object. */
            url: string;
            width: number;
            height: number;
            /** @description Short-lived signed GET URL that downloads the private WebP object as an attachment. */
            download_url: string;
        };
        /** @description The questionnaire a design is pinned to (null for legacy designs). */
        DesignQuestionnaire: {
            /** Format: uuid */
            id: string;
            version: number;
            schema: components["schemas"]["QuestionnaireSchema"];
        };
        /**
         * @description The purpose-built, curated concept result (Phase 12).
         *
         *     Deliberately excludes ``source_selections``, questionnaire answers,
         *     inspiration selections, the image prompt, prompt-builder version,
         *     DesignSpec provider/model, token counts, provider prediction id,
         *     provider/model name, seed, image parameters, staged metadata, storage
         *     keys, hashes, internal byte sizes, the user id, DesignSession id, the
         *     questionnaire version id, every signed URL and (Phase 14) the raw
         *     refinement note, refinement-request hash/schema version, seed reuse or
         *     source attempt.
         */
        DesignResult: {
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            design_version_id: string;
            version_number: number;
            title: string;
            concept_summary: string;
            garment_breakdown: components["schemas"]["GarmentBreakdownResult"];
            colour_story: components["schemas"]["ColourStoryResult"];
            fabrics_and_texture: components["schemas"]["FabricEntryResult"][];
            embellishment_plan: components["schemas"]["EmbellishmentPlanResult"];
            coverage_and_drape: components["schemas"]["CoverageAndDrapeResult"];
            cultural_context: components["schemas"]["CulturalContextResult"];
            styling_notes: string[];
            construction_caveats: string[];
            image_alt_text: string;
            /** Format: date-time */
            created_at: string;
            inspiration_acknowledgements: components["schemas"]["InspirationAcknowledgementResult"][];
            lineage: components["schemas"]["DesignVersionLineage"];
            is_demo: boolean;
        };
        DesignResultResponse: {
            result: components["schemas"]["DesignResult"];
        };
        DesignValidationSuccess: {
            valid: boolean;
        };
        DesignVersionImagesResponse: {
            images: components["schemas"]["DesignImages"];
        };
        /**
         * @description Since Phase 14: additive parent-child lineage for one result. A
         *     version with no parent (initial, or legacy) reports
         *     ``kind="initial"``/``parent_version_id=None``/``refinement=None``.
         */
        DesignVersionLineage: {
            kind: components["schemas"]["GenerationKindEnum"];
            /** Format: uuid */
            parent_version_id: string | null;
            refinement: components["schemas"]["RefinementLineage"] | null;
        };
        DesignWriteRequest: {
            title?: string;
            /** Format: uuid */
            questionnaire_version_id?: string;
            answers?: unknown;
            inspiration_asset_ids?: string[];
        };
        EmbellishmentPlanResult: {
            techniques: string[];
            density: string;
            placement: string[];
            motifs: string[];
            restraint_notes: string;
        };
        /**
         * @description * `demo_assets_unavailable` - demo_assets_unavailable
         *     * `design_changed` - design_changed
         *     * `design_incomplete` - design_incomplete
         *     * `generation_unavailable` - generation_unavailable
         *     * `image_download_failed` - image_download_failed
         *     * `image_ingest_failed` - image_ingest_failed
         *     * `image_ingest_unverified` - image_ingest_unverified
         *     * `image_output_invalid` - image_output_invalid
         *     * `image_poll_timeout` - image_poll_timeout
         *     * `image_prediction_aborted` - image_prediction_aborted
         *     * `image_prediction_canceled` - image_prediction_canceled
         *     * `image_prediction_failed` - image_prediction_failed
         *     * `image_provider_unavailable` - image_provider_unavailable
         *     * `image_staging_failed` - image_staging_failed
         *     * `image_staging_unverified` - image_staging_unverified
         *     * `image_submission_ambiguous` - image_submission_ambiguous
         *     * `internal_generation_error` - internal_generation_error
         *     * `prompt_build_failed` - prompt_build_failed
         *     * `queue_unavailable` - queue_unavailable
         *     * `refinement_generation_failed` - refinement_generation_failed
         *     * `refinement_invalid` - refinement_invalid
         *     * `refinement_limit_reached` - refinement_limit_reached
         *     * `refinement_no_change` - refinement_no_change
         *     * `refinement_source_unavailable` - refinement_source_unavailable
         *     * `structured_generation_failed` - structured_generation_failed
         *     * `structured_provider_refused` - structured_provider_refused
         *     * `structured_submission_ambiguous` - structured_submission_ambiguous
         * @enum {string}
         */
        ErrorCodeEnum: "demo_assets_unavailable" | "design_changed" | "design_incomplete" | "generation_unavailable" | "image_download_failed" | "image_ingest_failed" | "image_ingest_unverified" | "image_output_invalid" | "image_poll_timeout" | "image_prediction_aborted" | "image_prediction_canceled" | "image_prediction_failed" | "image_provider_unavailable" | "image_staging_failed" | "image_staging_unverified" | "image_submission_ambiguous" | "internal_generation_error" | "prompt_build_failed" | "queue_unavailable" | "refinement_generation_failed" | "refinement_invalid" | "refinement_limit_reached" | "refinement_no_change" | "refinement_source_unavailable" | "structured_generation_failed" | "structured_provider_refused" | "structured_submission_ambiguous";
        ErrorDetail: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Safe, user-facing message; never echoes secrets. */
            message: string;
        };
        /** @description The standard error body for 401/403/404/429/503 responses. */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        FabricEntryResult: {
            fabric: string;
            placement: string;
            finish_and_movement: string;
        };
        FieldValidationErrorDetail: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Safe, user-facing message. */
            message: string;
            /** @description Per-field validation messages keyed by field name. */
            fields?: {
                [key: string]: string[];
            };
        };
        GarmentBreakdownResult: {
            overall_form: string;
            garment_components: string[];
            silhouette: string;
            drape_or_layering: string;
            key_proportions: string;
        };
        /**
         * @description The stable public shape of one generation job (Phase 10).
         *
         *     Deliberately excludes every provider/storage provenance field (provider,
         *     model, prediction id, seed, parameters, storage key, image hash/size and
         *     the Celery task id) — only the lifecycle is public.
         */
        GenerationJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            design_version_id: string | null;
            status: components["schemas"]["StatusEnum"];
            error_code: (components["schemas"]["ErrorCodeEnum"] | components["schemas"]["NullEnum"]) | null;
            generation_kind: components["schemas"]["GenerationKindEnum"];
            is_demo: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
        };
        GenerationJobResponse: {
            job: components["schemas"]["GenerationJob"];
        };
        /**
         * @description * `initial` - initial
         *     * `refinement` - refinement
         * @enum {string}
         */
        GenerationKindEnum: "initial" | "refinement";
        /**
         * @description * `demo` - demo
         *     * `live` - live
         *     * `unavailable` - unavailable
         * @enum {string}
         */
        GenerationModeEnum: "demo" | "live" | "unavailable";
        /**
         * @description One private audit acknowledgement from the persisted, historical
         *     inspiration-context snapshot (Phase 13). Deliberately excludes the asset
         *     UUID, provider cues (garment type, visual description, cultural
         *     context), storage data and every URL — never reconstructed from the
         *     live catalogue, so a later asset retirement never rewrites it.
         */
        InspirationAcknowledgementResult: {
            position: number;
            title: string;
            attribution: string;
        };
        InspirationCatalogueResponse: {
            assets: components["schemas"]["PublicInspirationAsset"][];
        };
        LiveResponse: {
            /** @description Always "ok" when the process answers. */
            status: string;
            service: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LogoutResponse: {
            /** @description Always false after logout. */
            authenticated: boolean;
            /** @description Always null after logout. */
            user: components["schemas"]["AuthUser"] | null;
            /** @description Fresh anonymous token. */
            csrf_token: string;
        };
        MeResponse: {
            authenticated: boolean;
            /** @description The user when authenticated, else null. */
            user: components["schemas"]["AuthUser"] | null;
        };
        /** @enum {unknown} */
        NullEnum: null;
        /**
         * @description * `equals` - equals
         *     * `in` - in
         *     * `not_in` - not_in
         * @enum {string}
         */
        OperatorEnum: "equals" | "in" | "not_in";
        PatchedDesignWriteRequest: {
            title?: string;
            /** Format: uuid */
            questionnaire_version_id?: string;
            answers?: unknown;
            inspiration_asset_ids?: string[];
        };
        PublicConfig: {
            demo_mode: boolean;
            /** @description True only when environment gates AND a paid provider implementation allow it. */
            generation_enabled: boolean;
            /**
             * @description The public generation outcome. Demo takes precedence over every paid flag and never falls back to live.
             *
             *     * `demo` - demo
             *     * `live` - live
             *     * `unavailable` - unavailable
             */
            generation_mode: components["schemas"]["GenerationModeEnum"];
            max_inspiration_images: number;
            max_refinements: number;
        };
        PublicInspirationAsset: {
            /** Format: uuid */
            id: string;
            title: string;
            alt_text: string;
            garment_type: string;
            cultural_context: string;
            /** @description Approved public attribution text, if any. */
            attribution: string;
            /** @description Relative Django endpoint streaming WebP bytes. */
            image_url: string;
            /** @description Relative Django endpoint streaming WebP bytes. */
            thumbnail_url: string;
        };
        /**
         * @description Bounded per-question-type constraint mapping (all keys optional).
         *
         *     ``min_items``/``max_items``/``exclusive_values`` apply to ``multi_choice``;
         *     ``min_length``/``max_length`` apply to ``text``. Choice questions may omit
         *     constraints entirely.
         */
        QuestionConstraintsSchema: {
            min_items?: number;
            max_items?: number;
            exclusive_values?: string[];
            min_length?: number;
            max_length?: number;
        };
        QuestionOptionSchema: {
            /** @description Stable machine identifier persisted in answers. */
            value: string;
            label: string;
            description?: string;
        };
        QuestionSchema: {
            /** @description Stable machine identifier. */
            id: string;
            type: components["schemas"]["TypeEnum"];
            label: string;
            help_text?: string;
            required: boolean;
            /** @description Present for choice questions. */
            options?: components["schemas"]["QuestionOptionSchema"][];
            constraints?: components["schemas"]["QuestionConstraintsSchema"];
        };
        QuestionnaireSchema: {
            schema_version: number;
            key: string;
            title: string;
            steps: components["schemas"]["StepSchema"][];
            rules: components["schemas"]["CompatibilityRuleSchema"][];
        };
        ReadyChecks: {
            /** @description "ok" or "unavailable". */
            database: string;
            /** @description "ok" or "unavailable". */
            redis: string;
            /** @description "ok" or "unavailable". */
            auth_cache: string;
            /** @description "ok" or "unavailable". */
            storage: string;
        };
        ReadyResponse: {
            /** @description "ok" (200) or "unavailable" (503). */
            status: string;
            checks: components["schemas"]["ReadyChecks"];
        };
        /**
         * @description The refinement-specific lineage detail (Phase 14) for a version whose
         *     ``lineage.kind`` is ``"refinement"``. Deliberately excludes the raw
         *     optional note, the refinement-request hash, its schema version, the
         *     refinement template version, a seed and the source attempt.
         */
        RefinementLineage: {
            change_type: components["schemas"]["ChangeTypeEnum"];
        };
        /**
         * @description Coarse wire-shape validation for a refinement request (Phase 14):
         *     exactly ``source_version_id``, ``change_type`` and an optional ``note``.
         *
         *     Deliberately loose on ``change_type``/``note`` content — the strict
         *     allowlist/schema/safety-scan validation belongs to
         *     ``sitara.generation.refinement.normalise_refinement_request``, which the
         *     view calls next; this layer only rejects unknown fields and wrong JSON
         *     types, matching ``DesignWriteSerializer``'s pattern.
         */
        RefinementWriteRequest: {
            /** Format: uuid */
            source_version_id: string;
            change_type: string;
            /** @default  */
            note: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
        };
        /** @description A rule's ``then`` clause. */
        RuleActionSchema: {
            action: components["schemas"]["ActionEnum"];
            /** @description The question the action targets. */
            question_id: string;
            /** @description Option values; present only for restrict_options. */
            values?: string[];
        };
        /** @description A rule's ``when`` clause. */
        RuleConditionSchema: {
            /** @description The choice question this condition tests. */
            question_id: string;
            operator: components["schemas"]["OperatorEnum"];
            values: string[];
        };
        /**
         * @description One inspiration selection with its live availability.
         *
         *     ``available: false`` with ``asset: null`` means the previously-selected
         *     asset is no longer publicly eligible (retired, expired or revoked). The
         *     reason is deliberately not disclosed.
         */
        SelectedInspiration: {
            /**
             * Format: uuid
             * @description The selected inspiration asset id.
             */
            id: string;
            position: number;
            available: boolean;
            asset: components["schemas"]["SelectedInspirationAsset"] | null;
        };
        /** @description The public catalogue fields for an inspiration that is still eligible. */
        SelectedInspirationAsset: {
            /** Format: uuid */
            id: string;
            title: string;
            alt_text: string;
            garment_type: string;
            cultural_context: string;
            attribution: string;
            image_url: string;
            thumbnail_url: string;
        };
        /**
         * @description * `queued` - queued
         *     * `running_text` - running_text
         *     * `running_image` - running_image
         *     * `succeeded` - succeeded
         *     * `failed` - failed
         * @enum {string}
         */
        StatusEnum: "queued" | "running_text" | "running_image" | "succeeded" | "failed";
        StepSchema: {
            id: string;
            title: string;
            description?: string;
            questions: components["schemas"]["QuestionSchema"][];
        };
        /**
         * @description * `multi_choice` - multi_choice
         *     * `single_choice` - single_choice
         *     * `text` - text
         * @enum {string}
         */
        TypeEnum: "multi_choice" | "single_choice" | "text";
        /** @description The error body for 400 validation failures (adds ``fields``). */
        ValidationErrorEnvelope: {
            error: components["schemas"]["FieldValidationErrorDetail"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Login rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authentication cache unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Registration rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authentication cache unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    config_public: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    designs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignListResponse"];
                };
            };
        };
    };
    designs_create: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DesignWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignDetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Design workspace temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignDetailResponse"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_update: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDesignWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignDetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description design_not_editable: the design is no longer a draft (generating, generated, or a failed run with a version). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_generate: {
        parameters: {
            query?: never;
            header: {
                /** @description A client-generated UUID that makes the request idempotent PER DESIGN: repeating it returns the same job and queues no additional work. */
                "Idempotency-Key": string;
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description generation_in_progress / design_already_generated / design_not_generatable. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description generation_unavailable / queue_unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_refine: {
        parameters: {
            query?: never;
            header: {
                /** @description A client-generated UUID that makes the request idempotent PER DESIGN: repeating it returns the same job and queues no additional work. */
                "Idempotency-Key": string;
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefinementWriteRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description refinement_limit_reached / refinement_in_progress / refinement_source_unavailable / design_not_refinable. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description generation_unavailable / queue_unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_validate: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignValidationSuccess"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_version_images_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                design_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionImagesResponse"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description design_image_not_ready: no permanent image has been ingested yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description design_image_delivery_unavailable: not possible right now. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_version_result_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                design_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignResultResponse"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description design_result_not_ready: this design version has no complete result yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description design_result_unavailable: the stored content is corrupt, unsupported or unsafe. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description At least one dependency is unavailable; the body still lists each check. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    inspiration_assets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspirationCatalogueResponse"];
                };
            };
        };
    };
    inspiration_asset_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitised WebP image bytes streamed through Django. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description Missing or ineligible asset (indistinguishable from absent). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Eligible asset whose private storage object is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    inspiration_asset_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitised WebP image bytes streamed through Django. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description Missing or ineligible asset (indistinguishable from absent). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Eligible asset whose private storage object is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobResponse"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    questionnaire_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveQuestionnaireResponse"];
                };
            };
            /** @description No valid active questionnaire version is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
