/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap the CSRF token and browser session
         * @description Sets the sitara_csrftoken cookie and returns the matching token, and MATERIALISES the Django database session (setting sitara_sessionid) so later anonymous design operations can coordinate. Call this before any unsafe request. The token is never logged; the session key never leaves the backend.
         */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticates against a Django session. Failures for unknown email, wrong password and inactive accounts are one generic 401.
         */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Flushes the session and returns a fresh anonymous token. Idempotent: an anonymous browser gets the same shape of answer.
         */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session state
         * @description Browser session-state bootstrap. Returns the authenticated {id, email} user or an anonymous body — both are HTTP 200. Relies on the HttpOnly session cookie; anonymous access is intentional (no bearer token or API key is used).
         */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register and sign in
         * @description Creates an account and logs the browser in, rotating the session and token.
         */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public configuration
         * @description Safe, non-secret configuration for the frontend: demo mode, whether generation is available, and the inspiration/refinement limits. No authentication required; no tokens, credentials or storage details.
         */
        get: operations["config_public"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your designs
         * @description Returns the private designs owned by the current session or account. A list request never creates a workspace. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_list"];
        put?: never;
        /**
         * Create a design
         * @description Creates a private draft (title only; status and answers are server-owned). Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        post: operations["designs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/designs/{design_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a design
         * @description Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        get: operations["designs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a design
         * @description Title-only update. Ownership is by Django session (anonymous workspace) OR authenticated account — never by knowing a UUID. Anything inaccessible returns an indistinguishable 404.
         */
        patch: operations["designs_update"];
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process answers. No dependency checks. No authentication required.
         */
        get: operations["health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description PostgreSQL, the Redis broker, the auth-rate-limit cache and private object storage. Returns 503 with a displayable per-check body when any dependency is down. No authentication required.
         */
        get: operations["health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inspiration assets
         * @description Public, identity-free catalogue of rights-approved inspiration images (approved + verified + unexpired + all usage permissions). No authentication required; only the public fields are returned.
         */
        get: operations["inspiration_assets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/{asset_id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspiration asset image
         * @description Streams the full-size sanitised WebP for an eligible asset. No storage keys or storage URLs are exposed.
         */
        get: operations["inspiration_asset_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspiration-assets/{asset_id}/thumbnail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspiration asset thumbnail
         * @description Streams the thumbnail sanitised WebP for an eligible asset. No storage keys or storage URLs are exposed.
         */
        get: operations["inspiration_asset_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questionnaire/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active questionnaire
         * @description Serves the single active questionnaire version as {id, version, schema}. Public and identity-free (creates no session or workspace); no authentication required. The schema is the authoritative source of question types, constraints and compatibility rules.
         */
        get: operations["questionnaire_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `hide` - hide
         *     * `require` - require
         *     * `restrict_options` - restrict_options
         *     * `show` - show
         * @enum {string}
         */
        ActionEnum: "hide" | "require" | "restrict_options" | "show";
        ActiveQuestionnaireResponse: {
            /** Format: uuid */
            id: string;
            version: number;
            schema: components["schemas"]["QuestionnaireSchema"];
        };
        AuthSuccessResponse: {
            /** @description True on a successful login/registration. */
            authenticated: boolean;
            user: components["schemas"]["AuthUser"];
            /** @description Freshly rotated token to use going forward. */
            csrf_token: string;
        };
        AuthUser: {
            /**
             * Format: uuid
             * @description The user's UUID.
             */
            readonly id: string;
            /**
             * Format: email
             * @description Canonical (lower-cased) email.
             */
            readonly email: string;
        };
        CompatibilityRuleSchema: {
            id: string;
            when: components["schemas"]["RuleConditionSchema"];
            then: components["schemas"]["RuleActionSchema"];
        };
        CsrfResponse: {
            /** @description Send this back as the X-CSRFToken header on unsafe requests. */
            csrf_token: string;
        };
        DesignListResponse: {
            designs: components["schemas"]["DesignRead"][];
        };
        DesignRead: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly answers: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DesignWriteRequest: {
            title?: string;
        };
        ErrorDetail: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Safe, user-facing message; never echoes secrets. */
            message: string;
        };
        /** @description The standard error body for 401/403/404/429/503 responses. */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        FieldValidationErrorDetail: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Safe, user-facing message. */
            message: string;
            /** @description Per-field validation messages keyed by field name. */
            fields?: {
                [key: string]: string[];
            };
        };
        InspirationCatalogueResponse: {
            assets: components["schemas"]["PublicInspirationAsset"][];
        };
        LiveResponse: {
            /** @description Always "ok" when the process answers. */
            status: string;
            service: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LogoutResponse: {
            /** @description Always false after logout. */
            authenticated: boolean;
            /** @description Always null after logout. */
            user: components["schemas"]["AuthUser"] | null;
            /** @description Fresh anonymous token. */
            csrf_token: string;
        };
        MeResponse: {
            authenticated: boolean;
            /** @description The user when authenticated, else null. */
            user: components["schemas"]["AuthUser"] | null;
        };
        /**
         * @description * `equals` - equals
         *     * `in` - in
         *     * `not_in` - not_in
         * @enum {string}
         */
        OperatorEnum: "equals" | "in" | "not_in";
        PatchedDesignWriteRequest: {
            title?: string;
        };
        PublicConfig: {
            demo_mode: boolean;
            /** @description True only when environment gates AND a paid provider implementation allow it. */
            generation_enabled: boolean;
            max_inspiration_images: number;
            max_refinements: number;
        };
        PublicInspirationAsset: {
            /** Format: uuid */
            id: string;
            title: string;
            alt_text: string;
            garment_type: string;
            cultural_context: string;
            /** @description Approved public attribution text, if any. */
            attribution: string;
            /** @description Relative Django endpoint streaming WebP bytes. */
            image_url: string;
            /** @description Relative Django endpoint streaming WebP bytes. */
            thumbnail_url: string;
        };
        /**
         * @description Bounded per-question-type constraint mapping (all keys optional).
         *
         *     ``min_items``/``max_items``/``exclusive_values`` apply to ``multi_choice``;
         *     ``min_length``/``max_length`` apply to ``text``. Choice questions may omit
         *     constraints entirely.
         */
        QuestionConstraintsSchema: {
            min_items?: number;
            max_items?: number;
            exclusive_values?: string[];
            min_length?: number;
            max_length?: number;
        };
        QuestionOptionSchema: {
            /** @description Stable machine identifier persisted in answers. */
            value: string;
            label: string;
            description?: string;
        };
        QuestionSchema: {
            /** @description Stable machine identifier. */
            id: string;
            type: components["schemas"]["TypeEnum"];
            label: string;
            help_text?: string;
            required: boolean;
            /** @description Present for choice questions. */
            options?: components["schemas"]["QuestionOptionSchema"][];
            constraints?: components["schemas"]["QuestionConstraintsSchema"];
        };
        QuestionnaireSchema: {
            schema_version: number;
            key: string;
            title: string;
            steps: components["schemas"]["StepSchema"][];
            rules: components["schemas"]["CompatibilityRuleSchema"][];
        };
        ReadyChecks: {
            /** @description "ok" or "unavailable". */
            database: string;
            /** @description "ok" or "unavailable". */
            redis: string;
            /** @description "ok" or "unavailable". */
            auth_cache: string;
            /** @description "ok" or "unavailable". */
            storage: string;
        };
        ReadyResponse: {
            /** @description "ok" (200) or "unavailable" (503). */
            status: string;
            checks: components["schemas"]["ReadyChecks"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
        };
        /** @description A rule's ``then`` clause. */
        RuleActionSchema: {
            action: components["schemas"]["ActionEnum"];
            /** @description The question the action targets. */
            question_id: string;
            /** @description Option values; present only for restrict_options. */
            values?: string[];
        };
        /** @description A rule's ``when`` clause. */
        RuleConditionSchema: {
            /** @description The choice question this condition tests. */
            question_id: string;
            operator: components["schemas"]["OperatorEnum"];
            values: string[];
        };
        /**
         * @description * `draft` - Draft
         * @enum {string}
         */
        StatusEnum: "draft";
        StepSchema: {
            id: string;
            title: string;
            description?: string;
            questions: components["schemas"]["QuestionSchema"][];
        };
        /**
         * @description * `multi_choice` - multi_choice
         *     * `single_choice` - single_choice
         *     * `text` - text
         * @enum {string}
         */
        TypeEnum: "multi_choice" | "single_choice" | "text";
        /** @description The error body for 400 validation failures (adds ``fields``). */
        ValidationErrorEnvelope: {
            error: components["schemas"]["FieldValidationErrorDetail"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Login rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authentication cache unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSuccessResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Registration rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authentication cache unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    config_public: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    designs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignListResponse"];
                };
            };
        };
    };
    designs_create: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DesignWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DesignWriteRequest"];
                "multipart/form-data": components["schemas"]["DesignWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignRead"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Design workspace temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignRead"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    designs_update: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from GET /api/v1/auth/csrf/. Required on every unsafe (POST/PATCH) browser request; a missing or stale token yields 403 csrf_failed. */
                "X-CSRFToken": string;
            };
            path: {
                design_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDesignWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDesignWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedDesignWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignRead"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorEnvelope"];
                };
            };
            /** @description CSRF token missing/invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found or not owned (indistinguishable). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description At least one dependency is unavailable; the body still lists each check. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    inspiration_assets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspirationCatalogueResponse"];
                };
            };
        };
    };
    inspiration_asset_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitised WebP image bytes streamed through Django. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description Missing or ineligible asset (indistinguishable from absent). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Eligible asset whose private storage object is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    inspiration_asset_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitised WebP image bytes streamed through Django. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            /** @description Missing or ineligible asset (indistinguishable from absent). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Eligible asset whose private storage object is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    questionnaire_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveQuestionnaireResponse"];
                };
            };
            /** @description No valid active questionnaire version is available. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
